#!/usr/bin/perl
&init_words;
@password=getpwuid($<);
print "@password \n";
$name=$password[6];
$loginid=$password[0];
print "$loginid\n";
print "$name \n";
$name =~ s/.* //;
print "$name\n";
print "What is your name? ";
$name = <STDIN>;
chop ($name);
if ($name =~ /^randal\b/i) {
	print "Hello, Randal!! How good of you to be here!\n";
} else {
	print "Hello, $name!\n";
	print "What is the secret word? ";
	$guess = <STDIN>;
	chop ($guess);
	while (! &good_word ($name, $guess)) {
		print "Wrong, try again. What is the secret word? ";
		$guess = <STDIN>;
		chop ($guess);
	}
}

sub init_words {
	open (WORDLIST, "wordlist");
	if (-M WORDLIST > 7 ){
		die "Sorry, wordlist is older than seven days.";
	}
	while ($name = <WORDLIST>) {
		chop($name);
		$word = <WORDLIST>;
		chop ($word);
		$words{$name} = $word;
	}
	close (WORDLIST);
}

sub good_word {
	local ($somename, $someguess) = @_;	#name and initial params
	$somename =~ s/\W.*//;		# remove stuff after first Word
	$somename =~ tr/A-Z/a-z/;	#lowercase
	if ($somename eq "randal") {
		1;		#return true
	} elsif (($words{$somename} || "groucho") eq $someguess) {
		1;
	} else {
		open (MAIL, "|mail $loginid");
		print MAIL "bad news: $somename guessed $someguess\n";
		close (MAIL);
		0;
	}
}
